services:
  gateway:
    build: 
      dockerfile: ./server.dockerfile
      context: ./
    container_name: gateway_container
    ports:
      - "8000:8000"
  julia:
    build: 
      dockerfile: ./julia_engine.dockerfile
      context: ./
    container_name: julia_container
    ports:
      - "65432:65432"
  python:
    build: 
      dockerfile: ./py_engine.dockerfile
      context: ./
    container_name: py_container
    ports:
      - "8101:8101"